{
 "title": "Brigade_Criminelle_portfolio",
 "time": { "from": "2024-04-30T22:00:00.000Z", "to": "2026-04-30T22:00:00.000Z" },
 "panels": [
  {
   "title": "Affaires ouvertes depuis plus de 6 mois sans clôture :",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    dossier , \n    date_debut ,\n    type ,\n    statut \nFROM affaire\nWHERE date_fin IS NULL AND statut <> 'close'\nAND date_debut < NOW() - INTERVAL '6 months' ;"
    }
   ]
  },
  {
   "title": "Nombre moyen de pièces à conviction par affaire : ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG ( nb_piece_moy ) FROM (\n    SELECT af.dossier , COUNT( p.num_piece ) AS nb_piece_moy\n    FROM affaire af\n    LEFT JOIN piece p ON p.dossier = af.dossier \n    GROUP BY af.dossier \n) ;\n\n"
    }
   ]
  },
  {
   "title": "Répartition géographique des affaires par département : ",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT af.departement_code , d.nom_departement , d.latitude , d.longitude,COUNT(*) AS total_affaires\nFROM affaire af\nJOIN departement_geo d ON d.code_departement = af.departement_code\nGROUP BY af.departement_code, d.nom_departement, d.latitude ,d.longitude ; "
    }
   ]
  },
  {
   "title": "volume d'activité de la brigade dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('month', date_debut) AS time, \n    COUNT(dossier) AS value\nFROM affaire\nGROUP BY time\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Top 7 des Agents ayant traité le plus grand nombre d'affaires :",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT agm.nom , agm.prenom , agm.num_individu ,\nCOUNT( DISTINCT af.dossier ) AS nb_affaire\nFROM nom_agent_implique agm\nINNER JOIN affaire af ON agm.dossier = af.dossier\nGROUP BY agm.num_individu, agm.nom, agm.prenom\nORDER BY  nb_affaire DESC\nLIMIT 7 ;"
    }
   ]
  },
  {
   "title": "Individus impliqués dans plus d'une affaire : ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT i.nom , i.prenom , i.num_individu , COUNT(*)\nFROM individu i \nINNER JOIN implique im ON i.num_individu = im.num_individu\nGROUP BY i.nom , i.prenom , i.num_individu \nHAVING COUNT(*) > 1  ; "
    }
   ]
  },
  {
   "title": "Nombre d'affaires par type et par statut",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT af.type , af.statut , COUNT( af.dossier ) \nFROM affaire af\nGROUP BY af.type , af.statut ;\n"
    }
   ]
  }
 ]
}